name: Build Vue

on: [push]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Vue to Github Pages
      run: |
            yarn ci
            yarn build
            cd dist
            echo 'seffusanimat.us' > CNAME
            git config --global user.email "${{ inputs.gitemail }}"
            git config --global user.name "${{ inputs.gitname }}"
            git init
            git add -A
            git commit -m '${{ inputs.gitmsg }}'
            git push -f https://Stumblinbear:${{ secrets.GITHUB_TOKEN }}@github.com/Stumblinbear/SeffusAnimatus.git master:gh-pages
      shell: bash