name: Build Vue

on: [push]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Vue to Github Pages
      run: |
            yarn
            yarn build
            cd dist
            echo 'seffusanimat.us' > CNAME
            git config --global user.email "CI@example.com"
            git config --global user.name "CI"
            git init
            git add -A
            git commit -m 'Deploy'
            git push -f https://Stumblinbear:${{ secrets.GITHUB_TOKEN }}@github.com/Stumblinbear/SeffusAnimatus.git master:gh-pages
      shell: bash